- name: install python3 and pip
  dnf:
    name: 
      - python3
      - python3-pip
  state: present

- name: Make app directory 
  file:
    path: /opt/convert-txt-csv
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'
  
